---
driver_config:
  name: ec2
  region: eu-west-2
  require_chef_omnibus: true
  instance_type: t2.micro
  associate_public_ip: true
  chef_license: accept-no-persist

provisioner:
  name: chef_zero
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.12.3
  always_update_cookbooks: true

verifier:
  name: inspec
  chef_license: accept-no-persist

platforms:
- name: ubuntu-18.04
  driver:
    box: ubuntu/xenial64

suites:
- name: default
  run_list:
    - recipe[uber::default]
  verifier:
    inspec_tests:
      - test/integration/default
    chef_license: accept-no-persist
attributes:
