driver_config:
  name: ec2
  region: eu-west-2
  instance_type: t2.micro
  associate_public_ip: true
  require_chef_omnibus: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  log_level: info
  chef_license: accept-no-persist
  product_name: chef
  product_version: 14.10.9

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[uber::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
